### ISSUE TITLE
Could you transfer the project for develop continuously?

### ISSUE THREAD

**Issue by sumous** [pallets-eco/flask-session#101]
Hello,
   I found the project is not maintained for a long time, could you transfer the project for develop continuously?

**Comment by christopherpickering** [comment]
This project was transfered to pallets for future dev.

**Comment by davidism** [comment]
Flask-Session is now part of Pallets-Eco, an open source organization managed by the Pallets team to facilitate community maintenance of Flask extensions. Anyone interested in helping maintain this project can ask for commit access in the `#flask-session` channel on https://discord.gg/pallets.
