### ISSUE TITLE
Any way to retrieve data from filesystem session files?

### ISSUE THREAD

**Issue by adelyafatykhova** [pallets-eco/flask-session#104]
I'm using filesystem type and want to be able to access the data in the session file in a way that can be parsed or human readable.

These files look something like this now:
```
Systemic DesignîåNeutralîåUser Innovation / User DesignîåNeutralîå
Value Proposition CanvasîåAgreeîåWaterfall / Stage GateîåNeutralîuueuht}î(hås5îhåApplicationîhåÇ
This section is about the context.îh]î(}î(hj!��håq8îh å	frequencyîh!å;How frequently or infrequently do you use this method?îh"hh#å
```

Is there any way to be able to retrieve the data from such files?

For context, I had an instance where for my web app writing to the database was briefly not working - but the data I need was also being saved in the session.

**Comment by Varbin** [comment]
You may be able to decode the files with `pickle.load` from the standard library. `flask-session` users `werkzeug.contrib.cache` for the implementation of filesystem caching, which is based on `pickle`.

Example:
```python3
import pickle
with open("<filename>", "rb") as e:
    time = pickle.load(e)
    data = pickle.load(e)
```

**Comment by tassaron2** [comment]
Pickle should work. You can use also use whatever serializer is currently configured with `app.session_interface.serializer` (but default value for this is the pickle module so it's the same thing)

In my code I'm also using `want_bytes` imported from `itsdangerous`: `app.session_interface.serializer.loads(want_bytes(sessiondata))`
