### ISSUE TITLE
Explain why SESSION_USE_SIGNER might be needed

### ISSUE THREAD

**Issue by klahnakoski** [pallets-eco/flask-session#106]
Since the session data is stored on the server's side, I am at a loss why it would need to be signed.  Please update [the configuration doc](https://github.com/fengsp/flask-session/blob/master/docs/index.rst#configuration) (under SESSION_USE_SIGNER) with some reasoning.

Thank you

**Comment by frostming** [comment]
But the session id is transferred to client-side, and that is what the signer tries to encrypt.

**Comment by frostming** [comment]
Quoted from doc:

> Whether sign the session cookie sid or not, if set to True, you have to set

**Comment by yrro** [comment]
The setting probably exists to remain compatible with Flask's built in session feature, which stores the session data in a cookie.

If you are using Flask-Session and trust your server-side session store then you can probably get a tiny performance improvement by disabling `SESSION_USE_SIGNER`.
