### ISSUE TITLE
Imcomplete Documentation - Want to Contribute

### ISSUE THREAD

**Issue by djnorrisdev** [pallets-eco/flask-session#115]
When using Flask-Session, I noticed that it doesn't cover available methods or provide complete examples of usage. I had to find a blog post of a user that used the session.pop() method to remove a key from session storage. 

I would like to find out all available methods and contribute to the docs. Let me know how to do this, and I'll work on it.

**Comment by yrro** [comment]
AIUI, the `session` object provided by Flask-Session is API-compatible with Flask's built in `flask.session` object (after all, you access it in the same way, via `flask.session`).

[Flask's own documentation](https://flask.palletsprojects.com/en/2.0.x/api/#flask.session) states:

> The session object works pretty much like an ordinary dict, with the difference that it keeps track of modifications.

... which is the hint look at https://docs.python.org/3/library/stdtypes.html#mapping-types-dict which is where the `pop` method (and others) are defined.

I think there's a case for improving Flask's own documentation. IMO, if there is an improvement to be made in Flask-Session's documentation, it should probably just explicitly state that Flask-Session's `flask.session` is API-compatible with Flask's `flask.session` object and link back to Flask's own documentation.

**Comment by davidism** [comment]
Happy to consider PRs, in either project, but this issue is too broad on its own so I'm closing it.
