### ISSUE TITLE
csrf token missing error with wtforms on Windows

### ISSUE THREAD

**Issue by bobhumber-cbi** [pallets-eco/flask-session#120]
I have a Flask project running successfully using flask-session (using local storage) and Werkzeug 0.16.1 (I cannot uppdate to Werkzeug 1 because it removes the cache element).     If I update to flask-session 0.3.2, I get an error in wtforms  - Invalid: csrf_token.     This is despite the fact that I can see there is a string value stored in the session variable:

csrf_token   '15ee299c82185b98530b6c67e53e8271867933f8'

I have cachelib 0.1 installed

It is possible that this is to do with failure to store sessions, but it means I cannot use wtforms under Windows with Flask-Session 0.3.2

**Comment by psdon** [comment]
Same Here

**Comment by christopherpickering** [comment]
Please try again w/ the latest release and report back if it is still an issue.
