### ISSUE TITLE
Not able to set timeout for 'filesystem' session type

### ISSUE THREAD

**Issue by em-es-ce** [pallets-eco/flask-session#126]
Filesystem session type uses `cachelib.file` which allows for setting of a timeout:
https://github.com/pallets/cachelib/blob/master/cachelib/file.py#L38

However flask-session relies on the default parameter of the timeout and does not allow to adjust it:
https://github.com/fengsp/flask-session/blob/master/flask_session/sessions.py#L313

It would be great to be able to specify the timeout from flask-session (by for example a variable named SESSION_FILE_TIMEOUT)

**Comment by csm10495** [comment]
Folks, this isn't needed. If you dig into `FileSystemCache`, you'll find that `.set()` has an argument for timeout that is always set to `total_seconds(app.permanent_session_lifetime)`. Just set `app.permanent_session_lifetime`
