### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by steinsag** [pallets-eco/flask-session#128]
There hasn't been any update since a long time. There open issues and pull requests ready to get merged. Should we fork this repo?

**Comment by jdabtieu** [comment]
I think so. The owner hasn't been on GitHub for months now.

**Comment by billlyzhaoyh** [comment]
anyone going to take over this project?

**Comment by VeNoMouS** [comment]
@fengsp wake up and release the project if you don't intend in maintaining it anymore, the community is calling out to you!!

**Comment by yrro** [comment]
> @fengsp wake up and release the project if you don't intend in maintaining it anymore, the community is calling out to you!! theres 26 PR pending ffs

This is not a very nice way to ask someone to work for you for free.

The original maintainer hasn't updated this project for a long time, and that's fine. No one is entitled to their labour.

A benign fork incorporating the various PRs that have accumulated would be a great thing, but only if it has enough maintainers to survive. We don't want to end up with a repeat of the flask-sessionstore confusion... :)

**Comment by christopherpickering** [comment]
This was a great project and was appreciated by many!

Per GitHub, it looks like ***22k*** projects are actively using it! I came here a few days ago and also found that @fengsp has moved on from Flask. No problem, we all change tech at some point.

I could not find any active forks that incorporated all the requested features and fixes.

To keep the project going (and keep my projects going 😉) I started a fork and attempted to merge in most of the open PR's. I also updated the tests and a few old deps with something more modern.

https://pypi.org/project/flask-session2/
https://github.com/christopherpickering/flask-session2

If anyone is interested in being a maintainer as well, please reach out.

**Comment by fengsp** [comment]
Discussing the project future here: #156

**Comment by davidism** [comment]
Flask-Session is now part of Pallets-Eco, an open source organization managed by the Pallets team to facilitate community maintenance of Flask extensions. Anyone interested in helping maintain this project can ask for commit access in the `#flask-session` channel on httpd://discord.gg/pallets.
