### ISSUE TITLE
is this project dead

### ISSUE THREAD

**Issue by achaayb** [pallets-eco/flask-session#134]

**Comment by yrro** [comment]
Flask-Session has released 0.4.0 since the Flask-Sessionstore fork was created. It's not dead, it just doesn't have a great deal of development activity. :)

**Comment by eusoubrasileiro** [comment]
For me its dead 
```
miniconda3\lib\site-packages\flask_session\sessions.py", line 220, in _get_preferred_memcache_client
    return memcache.Client(servers)
AttributeError: module 'memcache' has no attribute 'Client'
```

**Comment by CJSparrow** [comment]
well the new one provide an error `ModuleNotFoundError: No module named 'werkzeug.contrib'`

**Comment by yrro** [comment]
> ```
> miniconda3\lib\site-packages\flask_session\sessions.py", line 220, in _get_preferred_memcache_client
>     return memcache.Client(servers)
> AttributeError: module 'memcache' has no attribute 'Client'
> ```

I guess the `MemcachedSessionInterface` class has bitrotted away. Looking at [the code](https://github.com/fengsp/flask-session/blob/67502d573be75710869c3eff226ebb9cec549a33/flask_session/sessions.py#L180) shows that [pylibmc](https://pypi.org/project/pylibmc/) will be used in preference to [memcache] if it's available, maybe try that.

Or extend the class and override `_get_preferred_memcache_client` with your own implementation that uses [pymemcache](https://pymemcache.readthedocs.io/en/latest/getting_started.html#basic-usage) (actually looking at that sample code makes me wonder if `memcache` was renamed to `pymemcache` at some point, and Flask-Session was never updated to match?

**Comment by jorgelaranjo** [comment]
> _No description provided._

> Session Storage Backends for the Flask Web Framework - **NO LONGER MAINTAINED**

**Comment by eusoubrasileiro** [comment]
Probably what everybody needs is this. [Flask-Caching recommended project](https://flask.palletsprojects.com/en/2.0.x/patterns/caching/)

**Comment by jorgelaranjo** [comment]
> Probably what everybody needs is [this](https://flask-caching.readthedocs.io/en/latest/). [Flask-Caching recommended project](https://flask.palletsprojects.com/en/2.0.x/patterns/caching/)

https://github.com/pallets-eco/flask-caching for source access.

**Comment by VeNoMouS** [comment]
> Probably what everybody needs is [this](https://flask-caching.readthedocs.io/en/latest/). [Flask-Caching recommended project](https://flask.palletsprojects.com/en/2.0.x/patterns/caching/)

requirement... meet rock

**Comment by yrro** [comment]
FYI, https://github.com/christopherpickering/flask-session2 is a new fork of `flask-session` that has merged a lot of outstanding PRs. The maintainer (@christopherpickering) is looking for co-maintainers, please reach out to him if you have any time to look after the new fork.

**Comment by darless** [comment]
Future project ownership discussed here: #156

**Comment by davidism** [comment]
Flask-Session is now part of Pallets-Eco, an open source organization managed by the Pallets team to facilitate community maintenance of Flask extensions. Anyone interested in helping maintain this project can ask for commit access in the `#flask-session` channel on httpd://discord.gg/pallets.
