### ISSUE TITLE
'session_cookie_name' is deprecated

### ISSUE THREAD

**Issue by b-simjoo** [pallets-eco/flask-session#150]
Hi, I'm using `flask_session` version 0.4.0 and Flask version 2.2.2, there is a warning that says:
> sessions.py:372: 'session_cookie_name' is deprecated and will be removed in Flask 2.3. Use 'SESSION_COOKIE_NAME' in 'app.config' instead.

**Comment by bmakan** [comment]
Flask `v2.3.0` dropped `session_cookie_name` from the `app` instance and this is now causing the flask to crash.

Temporary solution is not to use Flask v2.3+.

**Comment by igi-chris** [comment]
I started getting an error after deploying changes today:

> AttributeError: 'Flask' object has no attribute 'session_cookie_name'

As you mentioned, changing the flask version to 2.2.4 seems to resolve the issue for now.

**Comment by davidism** [comment]
Flask-Session 0.5.0 is now available.
