### ISSUE TITLE
Handover of package ownership.

### ISSUE THREAD

**Issue by Lxstr** [pallets-eco/flask-session#156]
@fengsp 
Let's get talking about where to have this package owned and maintained. You've done great work over the years but we need to find a future for this package.

@christopherpickering Would you consider merging your fork or something similar and taking over? is https://github.com/christopherpickering/flask-session2 the best current fork?

@davidism perhaps this might belong as part of the pallets family?

**Comment by Lxstr** [comment]
I have directly emailed Feng and hopefully he replies but are there any options if he doesn't?

**Comment by christopherpickering** [comment]
@Lxstr I try to keep the flask-session2 fork updated. I would be happy to merge back or give to another developer who is interested in continuing its use.

**Comment by davidism** [comment]
We have a https://github.com/pallets-eco for community maintenance of extensions. You're welcome to transfer it there, you'll retain ownership but others will be able to commit, and Pallets maintainers will be able to push to PyPI.

**Comment by Lxstr** [comment]
@davidism thank you that sounds quite good. Is there also an ownership strategy if for whatever reason they go MIA?

This seems the appropriate time to do something as latest flask release has broken Feng's package and the issues will be streaming in now.

Also, I noticed that there has been some pollution of the flask-session name. A few years ago this was unmaintained for a period and a fork was run at mcrowson/flask-sessionstore-fork which is now archived but is still connected to the highest SEO ranking documentation as flasksession.readthedocs.io vs flask-session.readthedocs.io, to the great confusion of anyone new. That dev is also unreachable: [https://github.com/fengsp/flask-session/issues/138](https://github.com/fengsp/flask-session/issues/138).

Over at pyrebase a similar thing happened (pyrebase4, pirebase, etc) but we have recently moved forwards with firebase-rest-api, which is a more accurate description anyway. It has just required telling people in the new issues and some blogging.

Long story in short, I am floating the idea of @christopherpickering doing a move to pallets-eco and a name change to say flask-server-side-session for the long term sake. Is this too much or what are the thoughts?

I'm not 100% on the best way to do this but possibly archiving flask-sessions2 and putting a deprecation warning in the short term. Ideally, the same on flask-session if we ever hear back.
```
import warnings
warnings.warn("Flask-session2 deprecated, please use flask-server-side-session", DeprecationWarning)
```

I'd be willing to help with readthedocs and awareness of the new home and/or name if there is support for that.

**Comment by fengsp** [comment]
@Lxstr Sorry for the late reply, It would be great if pallets-eco could help.

**Comment by fengsp** [comment]
Some updates:

- I would have a look at some breaking change required prs and merge them
- In the same time, it would be great that pallets-eco could help so I won't be the bottleneck for future maintenance

**Comment by davidism** [comment]
@fengsp I've sent you an invite to the github org, then you'll be able to transfer the repo. I'll also need full permission on PyPI, Test PyPI, and Read the Docs, my username is davidism on all of them.

@Lxstr were you planning to contribute to help get the next version out? Just transferring it to pallets-eco isn't enough, we need to find the community to continue contributions.

**Comment by darless** [comment]
@fengsp Thank you for replying to the email about transferring this repo to the pallets-eco. Thank you to @davidism for the quick reply to get things moving. I look forward to helping with this project where I can.

**Comment by fengsp** [comment]
@davidism  Repo transfer completed. Full permission on PyPI and Read the Docs added. We do not use Test PyPI for now.

**Comment by davidism** [comment]
Thank you. For community members who are interested in contributing, please join us at https://discord.gg/pallets in the #pallets-eco channel.

**Comment by christopherpickering** [comment]
If you'd like I can do a pr from flask-session2 which will close out many of the outstanding issues.

**Comment by davidism** [comment]
@christopherpickering @rayluo @Lxstr I've given you all write access. Together, we're still figuring out how pallets-eco will work. I've posted some ideas in Discord about first steps to making newly-added projects more maintainable, ping me there if you have any questions or suggestions.

**Comment by davidism** [comment]
Flask-Session is now part of Pallets-Eco, an open source organization managed by the Pallets team to facilitate community maintenance of Flask extensions. Anyone interested in helping maintain this project can ask for commit access in the `#flask-session` channel on https://discord.gg/pallets.
