### ISSUE TITLE
Can't reset sessions table between tests

### ISSUE THREAD

**Issue by nebolax** [pallets-eco/flask-session#175]
I am trying to run tests on my app that uses flask_session and I use sqlalchemy to store sessions data (it gets stored in `sessions` table).

If I run tests one-by-one, everything is fine. But if I run multiple tests, then starting at the second test and on I am getting error `sqlalchemy.exc.InvalidRequestError: Table 'sessions' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.`. And I am getting it even if I reset all tables in the db before / after every test.

What am I doing wrong and how can I solve this?

**Comment by christopherpickering** [comment]
@nebolax for a short term fix, I think you need what is updated in pr #170 👍🏽 
![image](https://github.com/pallets-eco/flask-session/assets/17788706/92f712e6-faac-4e91-b152-a105a9f07a3d)

You could update a fork for your project or use flask-session2 until this gets fixed here.

**Comment by nebolax** [comment]
Thanks for the suggestion @christopherpickering ! Unfortunately this does not help since the error happens at the point of initializing the session db model (`class Session(self.db.Model):`)

**Comment by nebolax** [comment]
I was able to solve this by executing `db.metadata.clear()` or `db.metadata._remove_table('sessions', your_schema_name)`

**Comment by nebolax** [comment]
@christopherpickering will it make sense to open a PR to fix this? In #170 this problem still exists

**Comment by nebolax** [comment]
Here is the pr #176. Looking forward for a review! @christopherpickering

**Comment by Lxstr** [comment]
Now fixed.
