### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sid'

### ISSUE THREAD

**Issue by 0x1618** [pallets-eco/flask-session#185]
line 542, in save_session

store_id = self.key_prefix + session.sid

AttributeError: 'NoneType' object has no attribute 'sid'

sometimes i randomly get this error. sqlalchemy.

**Comment by Lxstr** [comment]
Should now be prevented thanks to proper use of FlaskSessionInterface.should_set_cookie before saving session.
