### ISSUE TITLE
Changing cookie value changes key name in redis db

### ISSUE THREAD

**Issue by micahshell** [pallets-eco/flask-session#186]
I'm using flask-sessions to store sessions in redis and when in a browser if I change the cookie value in browser it changes the key name in the redis db. If I set SESSION_USE_SIGNER = True it fixes it but is there another way?

**Comment by Lxstr** [comment]
Hi @micahshell can you give me some more details please? I'm also wondering your use case for changing the cookie value in the browser? Can you walk me through exactly what you are seeing?

**Comment by Lxstr** [comment]
Closing due inactivity
