### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by saschapapini** [pallets-eco/flask-session#191]
Hi team, with Werkzeug 3.0.0 in my Flask application with Flask-sessions and SESSION_USE_SIGNER set to True on every request I receive the error

`  File "\env\Lib\site-packages\flask\app.py", line 1270, in process_response self.session_interface.save_session(self, ctx.session, response) File "\env\Lib\site-packages\flask_session\sessions.py", line 164, in save_session response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id, File "\env\Lib\site-packages\werkzeug\sansio\response.py", line 224, in set_cookie dump_cookie( File "\env\Lib\site-packages\werkzeug\http.py", line 1303, in dump_cookie if not _cookie_no_quote_re.fullmatch(value): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: cannot use a string pattern on a bytes-like object`

If I downgrade the Werkzeug version to 2.3.7 all work fine.

**Comment by enkelli** [comment]
See #189 and #194

**Comment by Lxstr** [comment]
Closed in favour of #189
