### ISSUE TITLE
sessions.py", line 164, in save_session       TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by devegowdatm** [pallets-eco/flask-session#200]
https://github.com/pallets-eco/flask-session/blob/09094d30cfa1aace46f93a192260940bf95cf97b/src/flask_session/sessions.py#L164
getting error  session.sid should be string but its bytes like object  when use_signer=True 
app.session_interface = RedisSessionInterface(
        app.cache,
        key_prefix=app.config.get('SESSION_CACHE_KEY_PREFIX', 'session:'),
        use_signer=True,
        permanent=app.config.get("SESSION_PERMANENT", True)
    )
version 0.5.0

**Comment by Lxstr** [comment]
Thanks for the issue, this is duplicate. Currently fixing
