### ISSUE TITLE
Session.expiry doesn't check for none

### ISSUE THREAD

**Issue by armurox** [pallets-eco/flask-session#204]
I noticed that in sessions.py, in line 557, the code read: 
`if saved_session and saved_session.expiry <= datetime.utcnow():`, which was causing issues when the flask session saved in the database was NULL (the line does not check for this case). This was affecting my ability to use sessions in supabase, so I have now changed the code to: `if saved_session and saved_session.expiry and saved_session.expiry <= datetime.utcnow():`. I have opened a pull request with this change, just wanted to make sure that I have gone about it the right way.

**Comment by Lxstr** [comment]
This one should now be fixed. Let me know if not

**Comment by armurox** [comment]
> This one should now be fixed. Let me know if not

@Lxstr yes, confirmed
