### ISSUE TITLE
Why does SqlAlchemySessionInterface take a table name but not a bind name?

### ISSUE THREAD

**Issue by leathakkor** [pallets-eco/flask-session#207]
It seems like 
```
        class Session(self.db.Model):
            __tablename__ = table
           ... 
```
            
should be more like:
```
        class Session1(self.db.Model):
            __tablename__ = table
            __bind_key__ = bind_key_name
```

If you are using sqlalchemy and want to store session in a separate database than your primary for whatever reason you would not be able to use this class out of the box. 

Perhaps this is already supported and I am simply missing it.

**Comment by Lxstr** [comment]
Added from 0.6.0
