### ISSUE TITLE
DynamoDB backend implementation.

### ISSUE THREAD

**Issue by necat1** [pallets-eco/flask-session#213]
Hey, i have implemented DynamoDBSessionInterface, and it works locally. How can i create PR? I don't have access to repo.

**Comment by Lxstr** [comment]
Hi there, you need to create a fork of flask session, push your feature branch (call it dynamodb) to your forked repo then create a pull request (preferably to development branch). Note that there have been quite a few changed on development branch that haven't been merged yet so you may need to rewrite slightly

**Comment by Lxstr** [comment]
Waiting for your PR. Closing this issue
