### ISSUE TITLE
`SqlAlchemySessionInterface` docstring and constructor arguments in 0.7.0rc2

### ISSUE THREAD

**Issue by Taragolis** [pallets-eco/flask-session#220]
Some inconsistencies into docstring and parameters in `SqlAlchemySessionInterface`

---

https://github.com/pallets-eco/flask-session/blob/c9579505223d5f45a633031ae257a8f2809802aa/src/flask_session/sqlalchemy/sqlalchemy.py#L62-L64

`db` argument is not valid argument in 0.7.0rc2

---

https://github.com/pallets-eco/flask-session/blob/c9579505223d5f45a633031ae257a8f2809802aa/src/flask_session/sqlalchemy/sqlalchemy.py#L65-L66

`cleanup_n_requests` - mentioned twice
`app` - I guess it exists from the very beginning. Or is it means that available `app` class instance now available?

**Comment by Lxstr** [comment]
Fixed in latest commits
