### ISSUE TITLE
>0.6.0 breaks session['last_active']

### ISSUE THREAD

**Issue by jeroen-80** [pallets-eco/flask-session#255]
For a session lifetime check I use the following code:
```
now = datetime.datetime.now()
delta = now - session['last_active'].replace(tzinfo=None)
[..]
```
Worked fine for years, until an upgrade to 0.8.0 (and a check on 0.7.0):
```
delta = now - session['last_active'].replace(tzinfo=None)
TypeError: replace() takes no keyword arguments
```
Seems that the type changed in 0.7.0? How to fix?

**Comment by Lxstr** [comment]
The changelog [https://flask-session.readthedocs.io/en/latest/changes.html](https://flask-session.readthedocs.io/en/latest/changes.html) and the rest of the documentation shows that the session itself has not changed types but the default serializer has for a number of reasons. This is also mentioned in the documentation. 

This means certain types may not serialize well as objects, you can see further infomation at the msgspec documentation. You could consider storing the last_active as a string and converting to datetime object. Hope that helps?

**Comment by jeroen-80** [comment]
> Hope that helps?

It does, thank you!
