### ISSUE TITLE
Interested in Contributors?

### ISSUE THREAD

**Issue by rsyring** [pallets-eco/flask-session#36]
We have a large app running on forked version of this project:

https://github.com/level12/flask-session/

I see there are a lot of open PRs.  Are you interested in adding a contributor or two to this repo & PyPI so we can help with pull requests and releases?

**Comment by blakev** [comment]
@rsyring what are the major differences? what have you added / changed?

**Comment by mcrowson** [comment]
This issue was moved to mcrowson/flask-session#6

**Comment by davidism** [comment]
Flask-Session is now part of Pallets-Eco, an open source organization managed by the Pallets team to facilitate community maintenance of Flask extensions. Anyone interested in helping maintain this project can ask for commit access in the `#flask-session` channel on httpd://discord.gg/pallets.
