### ISSUE TITLE
Upgrade from 0.2.3 to 0.3.0 breaks logins on Elastic Beanstalk

### ISSUE THREAD

**Issue by vision-mcgm** [pallets-eco/flask-session#44]
Hi,

With Flask 0.11.1, I just upgraded from Flask-session 0.2.3 to 0.3.0.

It breaks login, not on my local machine, but on EB.

On my local machine: a request to /login_required_page redirects to /login, then redirects to /login_required_page.

On Elastic Beanstalk: a request to /login_required_page redirects to /login, then redirects to /login_required_page, then redirects to /login_reqired_page&next=login_required_page. 

Logging in again causes the same error.

I am using flask-session for server-side sessions using Postgres.

**Comment by fengsp** [comment]
SqlAlchemySessionInterface is using LargeBinary type to store data now, I do not know whether
this information could solve your problem.

**Comment by mcrowson** [comment]
This issue was moved to mcrowson/flask-session#4

**Comment by Lxstr** [comment]
Outdated.
