### ISSUE TITLE
SqlAlchemy: TypeError if SESSION_PERMANENT=False

### ISSUE THREAD

**Issue by Ardius** [pallets-eco/flask-session#67]
Using SqlAlchemy (both with mysql and sqlite) if I set SESSION_PERMANENT to False the system return a TypeError 

```
File "/home/draio/project/venv/lib/python2.7/site-packages/flask_session/sessions.py", line 516, in open_session
     if saved_session and saved_session.expiry <= datetime.utcnow():
 TypeError: can't compare datetime.datetime to NoneType

```
Changing the SESSION_TYPE in filesystem the system works and the cookie will be deleted when the browser is closed.

On the DB table the session row has the _expiry_ row empty. 
_Expiry_ comes from _expires_ variable tha is set on row [547](https://github.com/fengsp/flask-session/blob/master/flask_session/sessions.py#L547):
` expires = self.get_expiration_time(app, session)`

[get_expiration_time](https://github.com/pallets/flask/blob/master/flask/sessions.py#L250) is a flask fuction that returns the expiration date for the session:
```
 if session.permanent:
            return datetime.utcnow() + app.permanent_session_lifetime

```
That's why the expiry field on sessions table is empty,  a cookie set as non-permanent doesn't have a expiration date. So it's not possible for mysql and sqlite to check a NULL date.

To populate the _expiry_ field in the DB table I changed:
`expires = self.get_expiration_time(app, session)`
into
```
expires = self.get_expiration_time(app, session) \
           or datetime.utcnow() + app.permanent_session_lifetime
```
No more error but if i close the browser the ,session cookie is still there.
That's because the [set_cookie](https://github.com/fengsp/flask-session/blob/master/flask_session/sessions.py#L561) function must have _expires_  empty to delete the cookie when browser is closed.

So I changed:
`expires = self.get_expiration_time(app, session)`
into
```
expires = self.get_expiration_time(app, session) \
           or datetime.utcnow() + app.permanent_session_lifetime
expires_cookie=expires if self.permanent else ''
```
And on line [561](https://github.com/fengsp/flask-session/blob/master/flask_session/sessions.py#L561) I changed:
```
response.set_cookie(app.session_cookie_name, session_id,
                    expires=expires, httponly=httponly,
                    domain=domain, path=path, secure=secure)
```
into
```
response.set_cookie(app.session_cookie_name, session_id,
                    expires=expires_cookie, httponly=httponly,
                    domain=domain, path=path, secure=secure)
```

I hope that this could by helpful and clear.

----------------------

**UPDATE**

Another way, more elegant,  to solve the problem is to check self.permanent before checking if saved_session.expire is outdated. 

On line [516](https://github.com/fengsp/flask-session/blob/master/flask_session/sessions.py#L516) change
`if saved_session and saved_session.expiry <= datetime.utcnow():`
into something like
`if self.permanent and saved_session and saved_session.expiry <= datetime.utcnow():`

Also this solution works but, if I'm not wrong, in this way the session will never be deleted from the DB table and, more important, it will never be tested. That's could be a security problem.

In the other solution the expiration date is written to the DB. In that case the problem may be that for a time a cookie remains active even if on the browser has already been deleted. I do not know if this could be considered a security problem.

----------------------

**UPDATE**  IE11 issue

On IE11 you cannot have a `Expires=;`, otherwise the cookie will never be stored.
For now I solved brutally with an `if` on
```
if not saved_session:
     if expires_cookie:
         response.set_cookie(app.session_cookie_name, session_id,
                                          expires=expires_cookie, httponly=httponly,
                                          domain=domain, path=path, secure=secure)
     else:
         response.set_cookie(app.session_cookie_name, session_id,
                                           httponly=httponly,
                                           domain=domain, path=path, secure=secure)
```

**Comment by NightBlues** [comment]
Same bug for mongodb backend.

**Comment by nagappan** [comment]
I made this fix for Mongo when testing with curl

        if document:
            expiration = document.get('expiration')
        else:
            expiration = None
        if document and expiration and expiration <= datetime.utcnow():

Worked for me

**Comment by zardilior** [comment]
@negappan could you pull request?

**Comment by macTracyHuang** [comment]
Same issue in PostgreSql

**Comment by DLAcoding** [comment]
Same here, solved with:
    
    if saved_session and saved_session.expiry:
        if saved_session.expiry<= datetime.utcnow():

**Comment by manugarri** [comment]
is there any way to fix this without changing the app code? We are experiencing this bug on AWS Airflow 2.4.3 and we cant really change airflow's version there

**Comment by Danipiario** [comment]
I have the same problem with a fresh installation on AWS Airflow 2.4.3
I've substituted in mwwa requirements flask-session lib with Flask-Session2 (https://github.com/christopherpickering/flask-session2), the code was changed in release 1.2.0 (https://github.com/christopherpickering/flask-session2/pull/4) due to this bug

**Comment by manugarri** [comment]
For what is worth, clearing browser data seems to 'fix' the issue

**Comment by Danipiario** [comment]
Yes, clearing the session data fix the access but temporarily until the session expires again. I've experienced the issue more times

**Comment by giom-l** [comment]
Hi @Danipiario , 
Did the update of flask-session lib in mwaa requirements fix the issue ? 
Or are you still encountering it in mwaa 2.4.3 despite the update ?

**Comment by Danipiario** [comment]
So far the workaround works

**Comment by wilminator** [comment]
FYI I have found a maintained fork of this project on Pypi [flask-session2](https://pypi.org/project/flask-session2/) that is actively maintained and does not have this problem. I was able to use it in my project as a drop-in replacement.

**Comment by Lxstr** [comment]
Fixed since 0.6.0. Please report any further issues

**Comment by HammadAwan424** [comment]
It doesn't give error but now nothing interesting happens. After setting up session, it returns None if you try to retrieve session data.

**Comment by Lxstr** [comment]
@HammadAwan424 can you show me a minimum example? Also can you try 0.7.0rc2? 

If you are upgrading from 0.5.0 while there are existing sessions, it will remove those sessions that had expiry None.
