### ISSUE TITLE
Session is gone every time a request come

### ISSUE THREAD

**Issue by unique1o1** [pallets-eco/flask-session#83]
Every time a new request comes in the previous session values that i set is gone. I'm using `SESSION_TYPE = 'filesystem' `and `SESSION_PERMANENT = True` as well. 

I'm using Free Heroku dyno for my chatbot.

**Comment by Baschdl** [comment]
Same problem here

**Comment by Baschdl** [comment]
Our problem was that we just used `SESSION_FILE_MODE = int('0700')` but this cuts of the leading zero so you've to use `SESSION_FILE_MODE = int('0700', 8)` which preserves the leading zero.
