### ISSUE TITLE
can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by GuyShaanan** [pallets-eco/flask-session#85]
I'm using `flask-session` with MongoDB (with the help of `Flask-PyMongo`).
`Flask-PyMongo` uses timezone-aware datetime objects.

From its [docs](https://flask-pymongo.readthedocs.io/en/latest/):

> Flask-PyMongo always uses timezone-aware datetime objects. That is, it sets the tz_aware parameter to True when creating a connection. The timezone of datetime objects returned from MongoDB will always be UTC.

`flask-session`, on the other hand, [compares](https://github.com/fengsp/flask-session/blob/090dc091aba699fe4661cc3b775f0ae99df35712/flask_session/sessions.py#L411) the `expires` value in the document against `datetime.utcnow()` which is **not** time zone aware.

Then the above exception is thrown:
```TypeError: can't compare offset-naive and offset-aware datetimes```

The workaround (that works for me) is to replace this line:
```python
if document and document.get('expiration') <= datetime.utcnow():
```

with these two lines:
```python
import pytz
if document and document.get('expiration') <= datetime.utcnow().replace(tzinfo=pytz.UTC):
```

----------------

A permanent solution _may_ be to examine `self.client.codec_options.tz_aware` (which is a boolean) and act accordingly.

---------------- 
flask == 0.12.2
Flask-PyMongo == 0.5.1
Flask-Session == 0.3.1

**Comment by Lxstr** [comment]
This should be fixed in 0.6.0 by forcing all pymongo datetimes to be tz_aware knowing that pymongo returns always utc time.
