### ISSUE TITLE
Regular SQLAlchemy instead of Flask-SQLAlchemy?

### ISSUE THREAD

**Issue by zefoo** [pallets-eco/flask-session#95]
I see under the hood this runs Flask-SQLAlchemy. 

Is it possible to use regular SQLAlchemy? I'm thinking no, I don't think it's a drop in replacement. 

If not, can I use Flask-SQLAlchemy *and* SQLAlchemy together? Where Flask-Session uses Flask-SQLAlchemy and everything else uses SQLAlchemy (and both share a connection string)?

**Comment by slastrina** [comment]
Flask session and flask-sqlalchemy work fine together, its how my current application is setup

you just need to assign the flask-sqlalchemy object to SESSION_SQLALCHEMY before you initialize the session object with app

init_db(app, db)
app.config['SESSION_SQLALCHEMY'] = db
sess.init_app(app)
db.create_all()

ive got the above in my appfactory. db is an flask-sqlalchemy object

**Comment by cal97g** [comment]
@slastrina he's saying he's not using flask-sqlalchemy but only *sqlalchemy*

**Comment by Lxstr** [comment]
Am open to a PR on this is anyone is willing

**Comment by Lxstr** [comment]
Closing as not planned unless there is a PR
